# Generated by Django 3.1.7 on 2021-03-07 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_date', models.DateField()),
                ('g_girl_num', models.IntegerField()),
                ('g_boy_num', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_gender', models.BooleanField(default=True)),
                ('s_age', models.IntegerField()),
                ('s_contend', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.grades')),
            ],
        ),
    ]
